import { IBaan, BaanSize } from '@/types/baan';

export const picTest1: string = '/images/rocket.svg'; //Pictures for testing...

export const testBaanData: IBaan[] = [
    //Test Data
    {
        id: 0,
        name: 'บ้านทรายทอง',
        size: BaanSize.Small,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 1,
        name: 'บ้านนี้มีรัก',
        size: BaanSize.Small,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 2,
        name: 'บ้านและสวน',
        size: BaanSize.Small,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 3,
        name: 'บ้านนอก',
        size: BaanSize.Small,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 4,
        name: 'บ้านของใคร',
        size: BaanSize.Medium,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 5,
        name: 'บ้านอะไรก็ไม่รู้',
        size: BaanSize.Medium,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 6,
        name: 'บ้านบ้าน',
        size: BaanSize.Large,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 7,
        name: 'บ้าน Pure',
        size: BaanSize.Large,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 8,
        name: 'บ้าน Dota',
        size: BaanSize.Large,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 9,
        name: 'บ้าน LOL',
        size: BaanSize.ExtraLarge,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 10,
        name: 'บ้าน ROV',
        size: BaanSize.ExtraLarge,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 11,
        name: 'บ้าน ggez',
        size: BaanSize.ExtraLarge,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 12,
        name: 'บ้าน HON',
        size: BaanSize.ExtraExtraLarge,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 13,
        name: 'บ้าน F',
        size: BaanSize.ExtraExtraLarge,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
    {
        id: 14,
        name: 'บ้าน U  ',
        size: BaanSize.ExtraExtraLarge,
        imageUrl: picTest1,
        description: '',
        facebook: '',
        ig: '',
        igUrl: '',
        facebookUrl: '',
    },
];
